title: Bharathksec-Blog
description: "Bharathksec Blog"
author:
  name: "Bharathksec"
  email: "bharathk7070@gmail.com"
  url: "https://bharathksec.github.io/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Bharathksec"
year : "2025"
